const coursesTypes = {
    LOAD_CREATOR_DRAFTS: "LOAD_CREATOR_DRAFTS",
    ADD_NEW_DRAFT_START: "ADD_NEW_DRAFT_START",
    VERIFY_COURSE_DRAFT_START: "VERIFY_COURSE_DRAFT_START",
    SET_IS_COURSE_VERIFIED: "SET_IS_COURSE_VERIFIED",
    SET_CREATOR_DRAFT: "SET_CREATOR_DRAFT",
}

export default coursesTypes