const coursesTypes = {
    GET_CREATOR_DRAFTS_START: "GET_CREATOR_DRAFTS_START",
    ADD_NEW_DRAFT_START: "ADD_NEW_DRAFT_START",
    VERIFY_COURSE_DRAFT_START: "VERIFY_COURSE_DRAFT_START",
    SET_IS_COURSE_VERIFIED: "SET_IS_COURSE_VERIFIED",
    SET_CREATOR_DRAFT: "SET_CREATOR_DRAFT",
    SET_CREATOR_COURSES: "SET_CREATOR_COURSES",
}

export default coursesTypes